# Transform univariate time series to supervised learning problem

In [1]:
from numpy import array

#### split a univariate sequence into samples

In [2]:
def split_sequence(sequence, n_steps):
    X, y = list(), list()
    for i in range(len(sequence)):
        # find the end of this pattern
        end_ix = i + n_steps
        
        # check if we are beyond the sequence
        if end_ix > len(sequence)-1:
            break
        
        # gather input and output parts of the pattern
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
        X.append(seq_x)
        y.append(seq_y)
        
    return array(X), array(y)

#### define univariate time series

In [3]:
series = array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(series.shape)

(10,)


#### transform to a supervised learning problem

In [4]:
X, y = split_sequence(series, 3)
print(X.shape, y.shape)

(7, 3) (7,)


#### show each sample

In [5]:
for i in range(len(X)):
    print(X[i], y[i])

[1 2 3] 4
[2 3 4] 5
[3 4 5] 6
[4 5 6] 7
[5 6 7] 8
[6 7 8] 9
[7 8 9] 10
